### ISSUE TITLE
Swipe between graphs

### ISSUE THREAD

**Issue by ltGuillaume** [albertvaka/bettercounter#10]
Would it be possible to add the option to swipe between the different graphs once opened for a counter? When reopened, the graph type as set in the counter options would show again, so that would become a "default" setting now.

**Comment by ltGuillaume** [comment]
> it would be nice to also be able to scroll to past data on the graph

Yes, I was thinking the exact same, sone time after I posted this, but I wasn't sure if you would be willing to look into that, too. I think we're on the exact same wavelength here.

**Comment by kypi** [comment]
I like this idea. What if I have a year's worth of data and I want to see a histogram of day in week or hour in day instead of monthly counts (by swiping on the data)? Is this what you're asking for @ltGuillaume ? Or are you thinking "I have lifetime information by month, but I want to see this week's  or day's counts"? I feel like both would be useful features to be able to quickly see depending on why you're counting/tracking things.

**Comment by ltGuillaume** [comment]
I don't really get the difference between your two examples tbh. I just think the current "fixed" setting per counter is rarely how I want to see my data: I'd like to be able to visualize it in all currently available ways and swipe back to previous days/weeks/months if possible.

**Comment by kypi** [comment]
From my understanding of the current implementation, if I change from lifetime to daily and look at the graph, it'll only show me details for the last day, but perhaps I want to know hourly details for the lifetime if I'm trying to determine trends of when certain counters happen.

**Comment by albertvaka** [comment]
This was added in https://github.com/albertvaka/bettercounter/pull/17, to be released in the following days.
