### ISSUE TITLE
Wrong average Because the latest count is factored in

### ISSUE THREAD

**Issue by unoukujou** [albertvaka/bettercounter#84]
![20241218_imgpipe_0](https://github.com/user-attachments/assets/5b573a72-ad38-492b-b636-04f7edf38b32)

![20241218_imgpipe_1](https://github.com/user-attachments/assets/2e9d744c-9610-4c26-9cb6-8e78c478939a)

In above example, I did something that lasted for 168 days. Today I did it again, and it dropped to 84 days average because this latest count is being factored in.

I suggest that the latest count should not be factored in to the average. because this is something that's going to take me for sure another 168 days to do it again yet the average shows that I do it every 84 days and it's misleading/inaccurate.

Or maybe, instead of the average, have a way to see how many days it was between the last time I did it and the current time. The number 168 is more important and useful for me to know than the number 84. Because 84 is a meaningless number in this chart. 168 is the average.

**Comment by albertvaka** [comment]
This is only a problem when you have very few datapoints. As soon as you have more, it will smoothen that out.

Also, imagine 168 more days have passed since your last count but you haven't counted again (you only have two counts). Now you do want to take into account the last count, since you want to see that you do this every 168 days and not every 336 days.

And finally, I think in general it would be more unexpected/confusing for the user to not count the last point that counting it.

**Comment by unoukujou** [comment]
In this example, I'm keeping track of how long a 45oz container of something has lasted me. It was 168 days. That's the important number that I need to know but the information is lost.

**Comment by albertvaka** [comment]
If you water the plants every 7 days exactly, on day 27 (before you have water the plants again in day 28), what is more accurate, 27/4 = every 6.25 days or 27/3 = every 9 days?

**Comment by unoukujou** [comment]
> If you water the plants every 7 days exactly, on day 27 (before you have water the plants again in day 28), what is more accurate, 27/4 = every 6.25 days or 27/3 = every 9 days? This happens if you don't count the last entry.

Neither is more accurate because nothing happened on day 27. Average is still 7 days.

In your example, you're calculating data that does not exist.

The average needs to be calculated one time at the point when the last data entry was made. Day 21 a record was made. After this point, there is nothing else ever need to be calculated until the next data entry is recorded on day 28.

Now in my example the 45 ounce container lasted 168 days. Let's say I don't want to do this experiment again. My experiment is finished on day 168 and I want to have this data recorded so I can look at it for future reference.

You only need to update the average on the day when someone adds a new record. It doesn't make sense to calculate the average every single day for the rest of eternity if someone stopped doing what they were doing.

Again, this is just my opinion of how I thought this app works. Maybe you have a different opinion. But for me, it's just not recording accurate data that I can go back and look at in the future and find accurate numbers.

**Comment by albertvaka** [comment]
I see. I'm more convinced now that what you propose makes sense, although I still see how someone (including myself) would want to know how often I do something counting until today even if I haven't done it today. It would be nice to know what other people think or would prefer. Maybe @MikeStirner you have an opinion?

**Comment by unoukujou** [comment]
Thanks. Yes, you can leave this issue open and see if anybody else says anything.

In your case, that you want to see everything counting until the today even if you haven't done it. You will still have this information, but it will be presented to you in a more useful way.

Think like this: In above example, watering the plants every 7 days. Your averaging 7 days exactly on day 21. On day 27 you will see the accurate average 7 days, you will also see the counter that you last done it 6 days ago. You will know that your average is 6 days and you've done it last 6 days ago. If you become lazy or forget to water the plant, maybe it is day 33 and still not done, you will see how you been averaging 7 day and you will see you last done it 12 days ago.

With this kind of information it's a lot better because you know if you're behind your average or if you're ahead of your average. And then if you do it on the 12th day then a new average will get calculated.

But the point is that bettercounter should calculate average based on only the data that was recorded.

Now in my next experiment, I want to keep track of different brand batteries and see which battery brand last the longest. But I can't use better counter to do this because after I'm done with the experiment all my data will become useless as the days go by it will continue to calculate and ruin all the data that I recorded. I need to keep accurate data for future reference.

**Comment by MikeStirner** [comment]
Yeah, I agree. The average should be calculated differently. It always confused to me, and now I understand why. Currently, the average is calculated as if I just hit the counter one more time, this instant, but... There are problems like you guys have been talking about. 

I think this would be a good change. And probably a pretty easy one, thankfully. 

And if I want it to return an average the old way, then I just simply hit the plus button one time, and then the new average will be like the old way. And then, if that was just to see the old average, then you could just hit the minus button to undo.

**Comment by unoukujou** [comment]
Yes. Exactly. I'm glad you see the point MikeStirner. I too was confused by the wrong average. 

Also, when we have the correct/accurate average, we can still see the current information that we did it last X days ago...

Then it's much more useful information. To know you're averaging Y days and you last done it X days ago, easily you can compare and know if you are ahead of your schedule or behind your schedule. It just makes more sense this way when you have the accurate average of "Y" days to use as your reference.

**Comment by albertvaka** [comment]
I guess this changes a bit if you are looking at historical data, though. Imagine you are scrolling back to see the counts of 6 months ago and there's only two counts, but after that month you might have continued counting. In that case, I think the average for the month should still be "every 15 days" because the month is complete and in that month only 2 counts ocurred. Or would you expect something else?

**Comment by albertvaka** [comment]
I've made the change, if you want to give it a try it is here: https://github.com/albertvaka/bettercounter/releases/tag/v4.9.99

**NOTE:** this is a version signed for the Google Play Store. If you use the app from F-Droid you won't be able to install this without uninstalling the app and erasing all your data first!

**Comment by unoukujou** [comment]
> I guess this changes a bit if you are looking at historical data, though. Imagine you are scrolling back to see the counts of 6 months ago and there's only two counts, but after that month you might have continued counting. In that case, I think the average for the month should still be "every 15 days" because the month is complete and in that month only 2 counts occurred. Or would you expect something else?

For my case, to know just the lifetime average is what matters. The average of the hour, month, year is not that important for me, but still can be calculated by just using the recorded data just from that month or that hour or that year to calculate the average for that complete time frame. I think even just keep it simple and just show the number stats for those historic data, could be enough. At least for me. I can't speak for anyone else. But for me, the only thing that matters is the lifetime average.

Thanks for the update. Yes I use the Fdroid version but I'm going to install this update on my other phone to test it out there. I'll see if I can export the data from this phone and put it on the other phone and see if it shows the average.

**Comment by unoukujou** [comment]
Hi, I just tested it and everything is perfect with this new release. The average is showing up correctly. Now this app is a lot more useful for keeping track of my numbers. Thanks.

**Comment by albertvaka** [comment]
I have pushed a new release including this change, thanks for the feedback! 🙂

**Comment by l3u** [comment]
Hi all,

this very change did actually break my use-case. I posted the issue here: https://github.com/albertvaka/bettercounter/issues/86 and I think this is the right place to elaborate this a bit more.

What I do is possibly the most basic use-case: I'm just interested in the average of something happening. Like, I want to know how many times, on average, I scratched my nose during a month.

Here's an example of the current behavior:

![Screenshot_20250104-003759](https://github.com/user-attachments/assets/7bdda4f7-09e4-4019-8a18-393a29e1c0f0)

Seven times on January 1st. Looking at this today, on January 4th, it tells me the average was "6.00 times a day". And that is simply plain wrong: For six times a day on average, I would need e.g. 7 times on 01-01, 5 times on 01-02, 6 times on 01-03 and 6 times on 01-04. Then, I would expect "6 times a day on average": (7 + 5 + 6 + 6) / 4 = 6.

But in the showed example, I have 7 times on one day, and 4 days. With nothing on the other days do far. So the correct average would be (7 + 0 + 0 +0) / 4, and that is 1.75 – not 6!

It also doesn't get better when adding additional values:

![Screenshot_20250104-003806](https://github.com/user-attachments/assets/af8c3da4-6c87-4b22-89dd-029daa04cee2)

Here, on January 4th, another increase was added. It now claims that the average was "1.75 times a day". But this is wrong again: What I would expect is (7 + 0 + 0 + 1) / 4, and that is 2 – not 1.75.

I see that there are apparently use-cases that need the changes discussed above. But this breaks basic average calculation like one (or at least I?!) would expect. So maybe, to address all use-cases, there should be an option for how to calculate the average? Either the basic, dumb "just what we have divided by the days" average I would like to see, or the "leave out the days until the next entry" average you need.

It would be really cool if this was solved somehow so that everybody is happy with it, as this app is really nice and convenient, without a real alternative. And I would be really happy if I could continue to use it :-)

Thanks in advance for working on this. And big thanks for maybe optionally restoring the original behavior!

Cheers, Tobias

**Comment by MikeStirner** [comment]
I'll reply over there on issue #86
